import './globals.css'
import { Inter, Raleway, Open_Sans } from 'next/font/google'
import Footer from './footer'
import Navbar from './navbar'

const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import { ReactQueryProvider } from './ReactQueryProvider'

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className={raleway.className}>
          <Navbar />
            {children}
          <Footer />
        </body>
      </html>
    </ReactQueryProvider>
  )
}
